### ISSUE TITLE
Chrome / Firefox compatibility

### ISSUE THREAD

**Issue by ciasto** [joomlaworks/radiowave-generic-player#2]
Hi,

I noticed that the player module once installed works with Safari browser only. It does "not click" when using Chrome / Firefox / Onion. 

Chrome returns this message with every attempt to click the "play" button:

Uncaught (in promise) DOMException: Failed to load because no supported source was found.

I am not a coder, only a front-end developer and I am not sure how to fix this.

Best,

Maciek

**Comment by kricore** [comment]
Hello Maciek,

Since this is a (free) part of a commercial template, can you open a ticket in the helpdesk so we can look into it?

**Comment by ciasto** [comment]
I am sorry, I am really new to this but at the same time I find this component extremely useful for my project.

How can I create a helpdesk ticket and with whom?

Best,

Maciek

**Comment by kricore** [comment]
This is actually a part of a Joomla! template called Radiowave, are you using this as a standalone player or as a part of Radiowave?

**Comment by ciasto** [comment]
Hi. Yes, indeed I am using a Joomla based Radiowave template (that I bought). However, I am not using RadioJar as a streaming server, so this extension was a real blessing. The website is rather simple at the moment, but you could see what I mean in different browsers:

http://www.thirdrail.fm.

It seems that Chrome / Firefox give error message when the play button is hit.

Let me know if I should Go to Radiowave developers webpage and try to open a ticket there or is it possible to do it here, at GitHub.

Best,

Maciek
